#!/bin/bash

python3 -m pip --disable-pip-version-check install virtualenv 

python3 -m venv venv
source venv/bin/activate
python3 -m pip --disable-pip-version-check install -r requirements.txt

pyinstaller --onefile --windowed main.py

touch STARS
echo '#!/bin/bash' >> STARS
echo 'DIR=$(cd "$(dirname "$0")"; pwd)' >> STARS
echo 'open $DIR/main' >> STARS

mkdir -p STARS.app/Contents/MacOS
cp STARS dist/main STARS.app/Contents/MacOS/
chmod +x STARS.app/Contents/MacOS/STARS
